### ISSUE TITLE
AssertionError: an attachment must be followed by a comment

### ISSUE THREAD

**Issue by dimpase** [svigerske/trac-to-github#2]
On https://trac.sagemath.org/ticket/7 one gets 
```
Migrate ticket #7 (5 changes): very strange bug with LaurentS
  created issue Issue(title="very strange bug with LaurentSeriesRing", number=28)
  comment by was ( -> )
  attachment by was ( -> 1790.patch)
  resolution by was ( -> fixed)
Traceback (most recent call last):
  File "./migrate.py", line 806, in <module>
    convert_issues(source, dest, only_issues = only_issues, blacklist_issues = blacklist_issues)
  File "./migrate.py", line 568, in convert_issues
    assert attachment is None or change_type == "comment", "an attachment must be followed by a comment"
AssertionError: an attachment must be followed by a comment
```

Is it because the attachment was added after the last comment? Or something else?

**Comment by dimpase** [comment]
yes, adding one more comment to the ticket in question allows the attachment to be imported. So this appears to be an easy logic adjustment to do.

**Comment by svigerske** [comment]
OK. I don't remember anything. Might be that this logic is even from the trac-to-gitlab that was the base of this, which was taken from somewhere else again...

The scripts will need adjustments for your usecase. If you have a fix for this issue or other general improvements, then I can merge them into here.

**Comment by svigerske** [comment]
I assume this has been taken care of in https://github.com/sagemath/trac-to-github. I've merged their changed into this repo now, too.
